// <auto-generated />
using System;
using EjerciciosVictorAPI.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EjerciciosVictorAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250314120905_CRUD_Clientes_Recibos")]
    partial class CRUD_Clientes_Recibos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EjerciciosVictorAPI.Entidades.Cliente", b =>
                {
                    b.Property<string>("DNI")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<decimal?>("CuotaMaxima")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("DNI");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("EjerciciosVictorAPI.Entidades.Recibo", b =>
                {
                    b.Property<string>("NumeroRecibo")
                        .HasColumnType("text");

                    b.Property<string>("ClienteDNI")
                        .IsRequired()
                        .HasColumnType("character varying(9)");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Importe")
                        .HasColumnType("numeric");

                    b.HasKey("NumeroRecibo");

                    b.HasIndex("ClienteDNI");

                    b.ToTable("Recibos");
                });

            modelBuilder.Entity("EjerciciosVictorAPI.Entidades.Recibo", b =>
                {
                    b.HasOne("EjerciciosVictorAPI.Entidades.Cliente", "Cliente")
                        .WithMany("Recibos")
                        .HasForeignKey("ClienteDNI")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("EjerciciosVictorAPI.Entidades.Cliente", b =>
                {
                    b.Navigation("Recibos");
                });
#pragma warning restore 612, 618
        }
    }
}
